### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by saswat0** [HazyResearch/hidden-stratification#5]
@nimz @stephenbach @henryre 

I'm getting an error while executing the demo code

```
PYTHONPATH=.:$PYTHONPATH python stratification/demo.py configs/demo_config.json
```

Full trace
```
Traceback (most recent call last):
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/jsonschema.py", line 85, in _check_type
    val, fpath = parse_value_or_config(val, enable_path=self._enable_path)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/util.py", line 147, in parse_value_or_config
    value = load_value(cfg_path.get_content(), simple_types=simple_types)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 111, in load_value
    loader = loaders[get_load_value_mode()]
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 102, in get_load_value_mode
    mode = parent_parser.get().parser_mode
LookupError: <ContextVar name='parent_parser' at 0x7f60013b1950>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stratification/demo.py", line 50, in <module>
    main()
  File "stratification/demo.py", line 12, in main
    config = get_config()
  File "/home/user/hidden-stratification/stratification/utils/parse_args.py", line 16, in get_config
    args = parser.parse_args(args_list)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/jsonschema.py", line 73, in __call__
    val = self._check_type(args[2])
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/jsonschema.py", line 93, in _check_type
    except (TypeError, ValueError) + get_jsonschema_exceptions() + get_loader_exceptions() as ex:
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 107, in get_loader_exceptions
    return loader_exceptions[get_load_value_mode()]
  File "/home/user/anaconda_3/envs/george_env/lib/python3.7/site-packages/jsonargparse/loaders_dumpers.py", line 102, in get_load_value_mode
    mode = parent_parser.get().parser_mode
LookupError: <ContextVar name='parent_parser' at 0x7f60013b1950>
```

**Comment by jennm** [comment]
This can be fixed by importing `ArgumentParser` from `jsonargparse` and setting `parser = ArgumentParser()`. This fixed the issue for me. Hope that helps! :)
